// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import ApplicationController from "./application_controller.js"
application.register("application", ApplicationController)

import ElementsController from "./elements_controller.js"
application.register("elements", ElementsController)

import HelloController from "./hello_controller.js"
application.register("hello", HelloController)

import PositionController from "./position_controller.js"
application.register("position", PositionController)

import PublisherController from "./publisher_controller.js"
import StimulusReflex from 'stimulus_reflex'
import consumer from '../channels/consumer'
import controller from '../controllers/application_controller'
import CableReady from 'cable_ready'
application.register("publisher", PublisherController)
application.consumer = consumer
StimulusReflex.initialize(application, { controller, isolate: true })
StimulusReflex.debug = process.env.RAILS_ENV === 'development'
CableReady.initialize({ consumer })