// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import ApplicationController from "./application_controller.js"
application.register("application", ApplicationController)

import ElementsController from "./elements_controller.js"
application.register("elements", ElementsController)

import HelloController from "./hello_controller.js"
application.register("hello", HelloController)

import PositionController from "./position_controller.js"
application.register("position", PositionController)

import PublisherController from "./publisher_controller.js"
application.register("publisher", PublisherController)
